config/routes.rb
Rails.application.routes.draw do
  get 'about/index', to: 'about#index'
  get 'home/index'
  get 'sectors/index'
  get 'sectors/show'
  get 'industries/index'
  get 'industries/show'
  get 'companies/index'
  get 'companies/show'
  #get '/about', to: 'static_pages#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  resources :companies, only: [:index, :show] do
    collection do
      get 'search' #companies/search/:id
    end
  end
  resources :industries, only: [:index, :show]
  resources :sectors, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :sector
  belongs_to :industry
end

app/models/industry.rb
class Industry < ApplicationRecord

  has_many :companies
  validates :name,presence: true, uniqueness: true
end

app/models/sector.rb
class Sector < ApplicationRecord

  has_many :companies
  validates :name,presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.includes(:industry, :sector).all.order("Rank_by_MarketCap")

  end

  def show
    @company = Company.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @companies = Company.where('name LIKE ?', wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies = Company.includes(:industry, :sector).order("Rank_by_MarketCap").limit(100)
    #@industries = Industry.limit(10)
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  def index
    @industries = Industry.select("industries.*")
                          .select("COUNT(industries.id) as company_count")
                          .left_joins(:companies)
                          .group("industries.id")
                          .order("industries.name")
  end

  def show
    @industry = Industry.find(params[:id])
    @companies = @industry.companies.order("Rank_by_MarketCap")
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  def index
    @sectors = Sector.select("sectors.*")
    .select("COUNT(sectors.id) as company_count")
    .left_joins(:companies)
    .group("sectors.id")
    .order("sectors.name")
  end

  def show
    @sector = Sector.find(params[:id])
    @companies = @sector.companies.order("Rank_by_MarketCap")
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  #include Kaminari::Helpers::HelperMethods
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/about/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Welcome to my website!</h1>
    <div class="content">
      <p>
        Here, I provide information about the top companies
        listed on NASDAQ. We use data from multiple sources including Kaggle and Yahoo Finance to
        give you a comprehensive overview of each company.
      </p>
      <p>
        My data is structured as follows:
      </p>
      <ul>
        <li>I have a table called "companies" that holds information about each company, such as its name, ticker symbol, stock price, share volumn, market cap, EPS, beta and its sector and industry.</li>
        <li>I also have a table called "industries" that information for all industries those top companies fall into</li>
        <li>Finally, I have a table called "sectors" that holds information for all sectors those top companies belong to.</li>
      </ul>
      <p>
        The data is related using the `companies` table as the primary key. The `industries` and `sectors` tables have a foreign key that links back to the `companies` table.
      </p>
      <p>
        Here's an ERD diagram that shows the relationships between the different tables in the database:
      </p>
      <%= image_tag("ERD.png", alt: "ERD diagram") %>
    </div>
  </div>
</section>

app/views/companies/index.html.erb
<h2 class="title is-3">NASDAQ Top 108 Companies Rank by Market Cap</h2>
<!--%= paginate @companies %-->
<div class="columns">
<ol class="ml-6">
  <% @companies.each do |m| %>
  <li>
  <%= link_to m.name, m %> with market cap of $<em><%= m.market_cap%></em>
  </li>
  <%end%>
</ol>
</div>
<!--%= paginate @companies %-->

app/views/companies/search.html.erb
<p class="mb-5">
  Companies found for: <%= params[:keywords] %>
  </p>
  <ul>
  <% @companies.each do |com|%>
  <li><%= link_to com.name, com %></li>
  <%end%>
  </ul>

app/views/companies/show.html.erb
<div class="ml-6">
<h1 class="title is-2"><%=@company.name %></h1>
<!--%= paginate @companies %-->
<p>
  <strong>Market Cap: </strong>
  $<%= @company.market_cap %>
</p>
<p>
  <strong>Price: </strong>
  $<%= @company.price %>
</p>
<p>
  <strong>
    Share Volumn:
  </strong>
  <%= @company.share_volume %> shares
</p>
<p>
  <strong>Symbol:</strong>
  <%= @company.symbol %>
</p>
<p>
  <strong>Beta:</strong>
  <%= @company.beta %>
</p>
<p>
  <strong>EPS:</strong>
  $<%= @company.eps %>
</p>
<% content_for(:html_title) {@company.name}%>
<p>
  <strong>
    Industry:
  </strong>
  <%= link_to @company.industry.name, @company.industry %>
</p>
<p>
  <strong>
    Sector:
  </strong>
  <%= link_to @company.sector.name, @company.sector %>
</p>
</div>

app/views/home/index.html.erb
<div>

  <div class="column">
    <h2 class="title is-2">Nasdaq Top 100 Companies Rank by Market Cap</h2>
    <ol class="ml-5">
      <% @companies.each do |c|%>
    <li>
      <%= link_to c.name, c%>
      <em>(<%= c.industry.name%>, <%= c.sector.name%>)</em>
    </li>
    <%end%>
    </ol>
    <p class="mt-3">
     <strong><%= link_to 'see the full list of 108 companies', companies_path%></strong>
    </p>
    <p class="mt-2">
     <strong><%= link_to 'see the full list of industries', industries_path%></strong>
    </p>
    <p class="mt-2">
     <strong><%= link_to 'see the full list of sectors', sectors_path%></strong>
    </p>
    </div>

</div>

app/views/industries/index.html.erb
<div class="ml-6">
<h1 class="title is-2">Industries</h1>
<ol>

  <% @industries.each do |i| %>
  <li>
    <%= link_to i.name, i  %>
    <em>(<%= pluralize i.company_count, "Company" %>)</em>
  </li>
  <%end%>
</ol>
</div>

app/views/industries/show.html.erb
<div class="ml-6">
<h1 class="title is-2"><%= @industry.name %></h1>
<p class='mb-5'>
    <%= pluralize @industry.companies.count, "company" %> within Top 109 Nasdaq companies in this industry
</p>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Symbol</th>
      <th>Market Cap</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.symbol %></td>
        <td>$<%= company.market_cap %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
  </head>
   <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to "Home - Nasdaq Top 100 Companies", root_path, class: "navbar-item" %>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">


          <a class="navbar-item" href="<%= companies_path %>">
            Companies
          </a>

          <a class="navbar-item" href="<%= industries_path %>">
            Industries
          </a>

          <a class="navbar-item" href="<%= sectors_path %>">
            Sectors
          </a>

          <a class="navbar-item" href="<%= about_index_path %>">
            About
          </a>
        </div>
      </div>
    </nav>

  <body><section>
      <div class="container">

      </div>
      <%= form_with(url: search_companies_path, method: :get, local:true) do %>
      <div class="field is-grouped mb-5">
      <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for companies")%>
      </div>
      <div class="control">
        <%= submit_tag("search", class:"button is_primary")%>
        </div>
      <%end%>
      <%= yield %>
      <!--%= paginate @companies, theme: 'bulma' %-->
    </section>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/sectors/index.html.erb
<div class="ml-6">
<h1 class="title is-2">Sectors</h1>
<ol>

  <% @sectors.each do |i| %>
  <li>
    <%= link_to i.name, i  %>
    <em>(<%= pluralize i.company_count, "Company" %>)</em>
  </li>
  <%end%>
</ol>
</div>

app/views/sectors/show.html.erb
<div class="ml-6">
<h1 class="title is-2"><%= @sector.name %></h1>
<p class='mb-5'>
    <%= pluralize @sector.companies.count, "company" %> within Top 109 Nasdaq companies in this sector
</p>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Symbol</th>
      <th>Market Cap</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.symbol %></td>
        <td>$<%= company.market_cap %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/shared/_footer.html.erb
<hr>
<footer>
<p>
<em>Copywrite by High-Tech Companies on NASDAQ</em>
</p>
<ul class="mt-3">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Companies', companies_path %></li>
  <li><%= link_to 'Industries', industries_path %></li>
  <li><%= link_to 'Sectors', sectors_path %></li>
  <li><%= link_to 'About', about_index_path %></li>
</ul>
</footer>

app/views/static_pages/about.html.erb
<h1>About Nasdaq Top Companies</h1>
<p>
  Nasdaq Top Companies is a web application that allows users to view the top 109 Nasdaq companies by market capitalization. The application was developed by [your name or company name] as a project to demonstrate web development skills.
</p>
<h2>ERD</h2>
<p>
  Below are the entity relationship diagrams (ERD) for the Nasdaq Top Companies database.
</p>
<div>
  <%= image_tag("ERD.png") %>
</div>